
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class SystemView extends javax.swing.JFrame {

private String cadena = "";
private String  operacion= " nula";
private double primerNumero,resultado;
private boolean activado=true;
private boolean punto = true;

    public SystemView() {
        initComponents();
        this.setTitle("Calculadora");
         setSize(310,470);
        // para que no manipule las diemenciones
      //  setResizable(false);
         this.setLocationRelativeTo(null); 
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNumeros = new javax.swing.JPanel();
        button_borrar = new javax.swing.JButton();
        button_raiz = new javax.swing.JButton();
        button_porcentaje = new javax.swing.JButton();
        button_divisior = new javax.swing.JButton();
        button_seven = new javax.swing.JButton();
        button_eight = new javax.swing.JButton();
        button_nine = new javax.swing.JButton();
        button_multiplicacion = new javax.swing.JButton();
        button_four = new javax.swing.JButton();
        button_five = new javax.swing.JButton();
        button_six = new javax.swing.JButton();
        button_resta = new javax.swing.JButton();
        button_one = new javax.swing.JButton();
        button_two = new javax.swing.JButton();
        button_three = new javax.swing.JButton();
        button_suma = new javax.swing.JButton();
        button_negativo = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        button_punto = new javax.swing.JButton();
        button_resultado = new javax.swing.JButton();
        labelprocess = new javax.swing.JLabel();
        labelresult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelNumeros.setLayout(new java.awt.GridLayout(5, 4));

        button_borrar.setForeground(new java.awt.Color(255, 0, 51));
        button_borrar.setText("C");
        button_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_borrarActionPerformed(evt);
            }
        });
        panelNumeros.add(button_borrar);

        button_raiz.setText(" √");
        button_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_raizActionPerformed(evt);
            }
        });
        panelNumeros.add(button_raiz);

        button_porcentaje.setText("%");
        button_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_porcentajeActionPerformed(evt);
            }
        });
        panelNumeros.add(button_porcentaje);

        button_divisior.setText("/");
        button_divisior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_divisiorActionPerformed(evt);
            }
        });
        panelNumeros.add(button_divisior);

        button_seven.setBackground(new java.awt.Color(153, 153, 153));
        button_seven.setText("7");
        button_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sevenActionPerformed(evt);
            }
        });
        panelNumeros.add(button_seven);

        button_eight.setBackground(new java.awt.Color(153, 153, 153));
        button_eight.setText("8");
        button_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eightActionPerformed(evt);
            }
        });
        panelNumeros.add(button_eight);

        button_nine.setBackground(new java.awt.Color(153, 153, 153));
        button_nine.setText("9");
        button_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nineActionPerformed(evt);
            }
        });
        panelNumeros.add(button_nine);

        button_multiplicacion.setText("*");
        button_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_multiplicacionActionPerformed(evt);
            }
        });
        panelNumeros.add(button_multiplicacion);

        button_four.setBackground(new java.awt.Color(153, 153, 153));
        button_four.setText("4");
        button_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fourActionPerformed(evt);
            }
        });
        panelNumeros.add(button_four);

        button_five.setBackground(new java.awt.Color(153, 153, 153));
        button_five.setText("5");
        button_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fiveActionPerformed(evt);
            }
        });
        panelNumeros.add(button_five);

        button_six.setBackground(new java.awt.Color(153, 153, 153));
        button_six.setText("6");
        button_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sixActionPerformed(evt);
            }
        });
        panelNumeros.add(button_six);

        button_resta.setText("-");
        button_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_restaActionPerformed(evt);
            }
        });
        panelNumeros.add(button_resta);

        button_one.setBackground(new java.awt.Color(153, 153, 153));
        button_one.setText("1");
        button_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_oneActionPerformed(evt);
            }
        });
        panelNumeros.add(button_one);

        button_two.setBackground(new java.awt.Color(153, 153, 153));
        button_two.setText("2");
        button_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_twoActionPerformed(evt);
            }
        });
        panelNumeros.add(button_two);

        button_three.setBackground(new java.awt.Color(153, 153, 153));
        button_three.setText("3");
        button_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_threeActionPerformed(evt);
            }
        });
        panelNumeros.add(button_three);

        button_suma.setText("+");
        button_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_sumaActionPerformed(evt);
            }
        });
        panelNumeros.add(button_suma);

        button_negativo.setText("+/-");
        button_negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_negativoActionPerformed(evt);
            }
        });
        panelNumeros.add(button_negativo);

        jButton18.setBackground(new java.awt.Color(153, 153, 153));
        jButton18.setText("0");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        panelNumeros.add(jButton18);

        button_punto.setText(".");
        button_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_puntoActionPerformed(evt);
            }
        });
        panelNumeros.add(button_punto);

        button_resultado.setText("=");
        button_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resultadoActionPerformed(evt);
            }
        });
        panelNumeros.add(button_resultado);

        labelprocess.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelprocess.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelprocess.setText("0");
        labelprocess.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        labelresult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelresult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelprocess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelresult, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelprocess, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_puntoActionPerformed
        // punto
        if (punto==true) {
            if (cadena.equals("")) {
                cadena="0.";
                
            }else{
                cadena +=".";

            }
            labelprocess.setText(cadena);
             punto=false;
        }
       
    }//GEN-LAST:event_button_puntoActionPerformed

    private void button_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eightActionPerformed
        // ocho
           if (labelprocess.getText().equals("0")) {
            cadena="8";
        }else{
            cadena+="8";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    
    }//GEN-LAST:event_button_eightActionPerformed

    private void button_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sevenActionPerformed
        // siete
        if (labelprocess.getText().equals("0")) {
            cadena="7";
        }else{
            cadena+="7";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_sevenActionPerformed

    private void button_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sumaActionPerformed
        // mas
        if (activado==true) {
            primerNumero=Double.parseDouble(cadena);
            labelresult.setText(cadena+"+");
            cadena="";
            operacion="sumar";
            activado =false;
            punto=true;
        }
    }//GEN-LAST:event_button_sumaActionPerformed

    private void button_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resultadoActionPerformed
        //igual
        double segundonumero=0;
        if (operacion.equals("nula")) {
            labelprocess.setText(cadena);
        }else
        if (operacion=="sumar") {
            segundonumero=Double.parseDouble(cadena);
            resultado=primerNumero+segundonumero;
            labelprocess.setText(String.format("% .2f", resultado));
        cadena=String.valueOf(resultado);
       
        operacion="nula";
        }else
        if (operacion=="restar") {
            segundonumero=Double.parseDouble(cadena);
            resultado=primerNumero-segundonumero;
            labelprocess.setText(String.format("% .2f", resultado));
        cadena=String.valueOf(resultado);
        }else
        if (operacion=="multiplicar") {
            segundonumero=Double.parseDouble(cadena);
            resultado=primerNumero*segundonumero;
            labelprocess.setText(String.format("% .2f", resultado));
        cadena=String.valueOf(resultado);
        }else
        if (operacion=="dividir") {
            segundonumero=Double.parseDouble(cadena);
            if (segundonumero==0) {
                JOptionPane.showInternalMessageDialog(null, "No se puede dividir entre 0");
            }else{
                  resultado=primerNumero/segundonumero;
            labelprocess.setText(String.format("% .2f", resultado));
        cadena=String.valueOf(resultado);
            }
        }else
        if (operacion=="porciento") {
    
               segundonumero=Double.parseDouble(cadena);
            resultado=(primerNumero/100)*segundonumero;
            labelprocess.setText(String.format("% .0f", resultado));
        cadena=String.valueOf(resultado);
            
        }
        operacion="nula";
         
        labelresult.setText("");
        activado=true;
       
          
    }//GEN-LAST:event_button_resultadoActionPerformed

    private void button_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nineActionPerformed
        // nueve
          if (labelprocess.getText().equals("0")) {
            cadena="9";
        }else{
            cadena+="9";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_nineActionPerformed

    private void button_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fourActionPerformed
        // cuatro
          if (labelprocess.getText().equals("0")) {
            cadena="4";
        }else{
            cadena+="4";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_fourActionPerformed

    private void button_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fiveActionPerformed
        // cinco
          if (labelprocess.getText().equals("0")) {
            cadena="5";
        }else{
            cadena+="5";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_fiveActionPerformed

    private void button_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_sixActionPerformed
        // seis
          if (labelprocess.getText().equals("0")) {
            cadena="6";
        }else{
            cadena+="6";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_sixActionPerformed

    private void button_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_oneActionPerformed
        // uno
          if (labelprocess.getText().equals("0")) {
            cadena="1";
        }else{
            cadena+="1";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_oneActionPerformed

    private void button_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_threeActionPerformed
        // tres
          if (labelprocess.getText().equals("0")) {
            cadena="3";
        }else{
            cadena+="3";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_threeActionPerformed

    private void button_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_twoActionPerformed
        // dos
          if (labelprocess.getText().equals("0")) {
            cadena="2";
        }else{
            cadena+="2";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_button_twoActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // cero
          if (labelprocess.getText().equals("0")) {
            cadena="0";
        }else{
            cadena+="0";
        }
        labelprocess.setText(cadena);
        activado=true;//para seguir usando la calculadora
    }//GEN-LAST:event_jButton18ActionPerformed

    private void button_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_restaActionPerformed
    //menos
       if (activado==true) {
            primerNumero=Double.parseDouble(cadena);
            labelresult.setText(cadena+"-");
            cadena="";
            operacion="restar";
            activado =false;
          
        }
    }//GEN-LAST:event_button_restaActionPerformed

    private void button_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_multiplicacionActionPerformed
        // multiplicar 
           if (activado==true) {
            primerNumero=Double.parseDouble(cadena);
            labelresult.setText(cadena+"*");
            cadena="";
            operacion="multiplicar";
            activado =false;
           
        } 
    }//GEN-LAST:event_button_multiplicacionActionPerformed

    private void button_divisiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_divisiorActionPerformed
        //divifir
           if (activado==true) {
            primerNumero=Double.parseDouble(cadena);
            labelresult.setText(cadena+"/");
            cadena="";
            operacion="dividir";
          
        
        }
    }//GEN-LAST:event_button_divisiorActionPerformed

    private void button_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_raizActionPerformed
        // raiz
        primerNumero=Double.parseDouble(cadena);
        labelresult.setText(" √("+cadena+")");
        resultado=Math.sqrt(primerNumero);
        labelprocess.setText(String.format("% .2f", resultado));
        cadena=String.valueOf(resultado);
         activado =false;
    }//GEN-LAST:event_button_raizActionPerformed

    private void button_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_porcentajeActionPerformed
        // porciento
           if (activado==true) {
            primerNumero=Double.parseDouble(cadena);
            labelresult.setText(cadena+"%");
            cadena="";
            operacion="porciento";
          
           activado =false;
        }
    }//GEN-LAST:event_button_porcentajeActionPerformed

    private void button_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_borrarActionPerformed
        // clear
        labelprocess.setText("");
        labelresult.setText("");
      operacion="nula";
      cadena="";
      activado=true;
      punto=true;
    }//GEN-LAST:event_button_borrarActionPerformed

    private void button_negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_negativoActionPerformed
        // mas menos
        if (cadena.charAt(0)!='-') {
            cadena="-"+cadena;
        }else{
            cadena=cadena.substring(1,cadena.length());
            
        }
        labelprocess.setText(cadena);
    }//GEN-LAST:event_button_negativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     // implentacion de diseño
      try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_borrar;
    private javax.swing.JButton button_divisior;
    private javax.swing.JButton button_eight;
    private javax.swing.JButton button_five;
    private javax.swing.JButton button_four;
    private javax.swing.JButton button_multiplicacion;
    private javax.swing.JButton button_negativo;
    private javax.swing.JButton button_nine;
    private javax.swing.JButton button_one;
    private javax.swing.JButton button_porcentaje;
    private javax.swing.JButton button_punto;
    private javax.swing.JButton button_raiz;
    private javax.swing.JButton button_resta;
    private javax.swing.JButton button_resultado;
    private javax.swing.JButton button_seven;
    private javax.swing.JButton button_six;
    private javax.swing.JButton button_suma;
    private javax.swing.JButton button_three;
    private javax.swing.JButton button_two;
    private javax.swing.JButton jButton18;
    public javax.swing.JLabel labelprocess;
    public javax.swing.JLabel labelresult;
    private javax.swing.JPanel panelNumeros;
    // End of variables declaration//GEN-END:variables
}
